### ISSUE TITLE
Instruction requires: pa when compiling

### ISSUE THREAD

**Issue by avltree9798** [ZecOps/public#1]
Hi, I can't compile this project. The XCode gives me this error.
<img width="279" alt="Screen Shot 0001-11-29 at 22 54 08" src="https://user-images.githubusercontent.com/16130362/69879886-28462b80-12fb-11ea-8b40-b39415f8f619.png">
<img width="831" alt="Screen Shot 0001-11-29 at 22 54 30" src="https://user-images.githubusercontent.com/16130362/69879903-34ca8400-12fb-11ea-880d-4deea84b89b5.png">

**Comment by tomitokics** [comment]
What device is this ?

**Comment by avltree9798** [comment]
> What device is this ?

I tried to compile this on my MBP 2017

**Comment by tomitokics** [comment]
> > What device is this ?
> 
> I tried to compile this on my MBP 2017

Ok, but are you trying to compile this to a physical device, or you are trying to run it on simulator?

**Comment by avltree9798** [comment]
> > > What device is this ?
> > 
> > 
> > I tried to compile this on my MBP 2017
> 
> Ok, but are you trying to compile this to a physical device, or you are trying to run it on simulator?

To a physical device

**Comment by tomitokics** [comment]
What device ?

**Comment by tomitokics** [comment]
> What device ?

And I'm mean eg. iXs

**Comment by avltree9798** [comment]
> What device ?

iPhone 8

**Comment by tomitokics** [comment]
> > What device ?
> 
> iPhone 8

Ok, so the iPhone 8 is A11 right? And you are trying to execute i.e "pacdza" which is not available on A11 SoC as it needs Pointer Authentication (pa) (so it will compile from A12 < ).
Remove the functions that make use of pointer authentication and you should be able to compile.
